version: "3.8"

services:


  db:
    build: db/postgres/
    container_name: "imdb_game-postgres"
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 45s
      interval: 10s
      retries: 10

  web:
    build: .
    container_name: "imdb_game-webserver"
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy