version: "3.8"
# For local running of the application
volumes:
  mongo:
    name: mongo

services:
  mongo:
    build: db/
    container_name: "imdb-game-mongodb"
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    container_name: "imdb-game-webserver"
    ports:
      - "80:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
